# Generated by Django 2.2.19 on 2021-04-06 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminid', models.AutoField(db_column='AdminID', primary_key=True, serialize=False)),
                ('adminname', models.CharField(db_column='AdminName', default='giru', max_length=50, verbose_name='Name')),
            ],
            options={
                'db_table': 'Admin',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'Amenities',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'Facilities',
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('host_id', models.AutoField(db_column='Host_ID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, db_column='First_Name', max_length=30, null=True, verbose_name='First')),
                ('last_name', models.CharField(blank=True, db_column='Last_Name', max_length=30, null=True, verbose_name='Last')),
            ],
            options={
                'db_table': 'Host',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HouseRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'House Rule',
            },
        ),
        migrations.CreateModel(
            name='Roomtype',
            fields=[
                ('roomtypeid', models.AutoField(db_column='RoomTypeID', primary_key=True, serialize=False)),
                ('roomtype', models.CharField(blank=True, db_column='RoomType', max_length=20, null=True, verbose_name='Type')),
            ],
            options={
                'db_table': 'RoomType',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Traveller',
            fields=[
                ('traveller_id', models.AutoField(db_column='Traveller_ID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, db_column='First_Name', max_length=30, null=True, verbose_name='First')),
                ('last_name', models.CharField(blank=True, db_column='Last_Name', max_length=30, null=True, verbose_name='Last')),
            ],
            options={
                'db_table': 'Traveller',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('rentid', models.AutoField(db_column='RentID', primary_key=True, serialize=False)),
                ('account', models.CharField(blank=True, db_column='Account', max_length=1, null=True)),
                ('from_date', models.DateTimeField(blank=True, db_column='From_Date', null=True, verbose_name='Check-In Date')),
                ('to_date', models.DateTimeField(blank=True, db_column='To_Date', null=True, verbose_name='Check-Out Date')),
                ('isactive', models.NullBooleanField(db_column='ISactive')),
                ('roomtypeid', models.ForeignKey(blank=True, db_column='RoomTypeID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='posts.Roomtype')),
            ],
            options={
                'db_table': 'Rent',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('apartid', models.AutoField(db_column='apartID', primary_key=True, serialize=False)),
                ('name', models.TextField(default='', max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('house_rules', models.TextField(default='', help_text='Put your house rules here', max_length=100)),
                ('summary', models.TextField(help_text='Enter a brief description of the item', max_length=1000)),
                ('is_reserved', models.NullBooleanField(db_column='IS_Reserved')),
                ('status', models.CharField(blank=True, choices=[('A', 'Available'), ('O', 'Occupied')], default='a', help_text='Item availability', max_length=1)),
                ('roomtype', models.ForeignKey(db_column='RoomType', on_delete=django.db.models.deletion.DO_NOTHING, to='posts.Roomtype', verbose_name='Room Type')),
                ('tags', models.ManyToManyField(related_name='apartments', to='posts.Tag')),
            ],
            options={
                'db_table': 'APARTMENT',
                'managed': True,
            },
        ),
    ]
