# Generated by Django 2.2.19 on 2021-04-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='avatar',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
