# Generated by Django 2.2.19 on 2021-04-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210328_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'Amenities',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'Facilities',
            },
        ),
        migrations.CreateModel(
            name='HouseRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'House Rule',
            },
        ),
        migrations.AlterModelOptions(
            name='apartment',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='apartment',
            name='house_rules',
            field=models.TextField(default='', help_text='Put your house rules here', max_length=100),
        ),
        migrations.AddField(
            model_name='apartment',
            name='name',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='apartment',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='apartment',
            table='APARTMENT',
        ),
    ]
