# Generated by Django 2.2.19 on 2021-04-07 13:15

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_apartment_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='avatar',
            field=sorl.thumbnail.fields.ImageField(upload_to='whatever'),
        ),
    ]
