# Generated by Django 2.2.19 on 2021-04-07 13:26

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210407_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='avatar',
            field=sorl.thumbnail.fields.ImageField(default=0, upload_to='whatever'),
            preserve_default=False,
        ),
    ]
