# Generated by Django 2.2.19 on 2021-04-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='tags',
            field=models.ManyToManyField(related_name='apartments', to='posts.Tag'),
        ),
    ]
