# Generated by Django 2.2.19 on 2021-04-07 13:29

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210407_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=sorl.thumbnail.fields.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
